apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      initContainers:
      - name: init-verify-redis-service-dns
        image: busybox:latest
        command: ['nslookup', 'redis-service.default.svc.cluster.local']
      - name: init-verify-redis-ready
        image: busybox:latest
        command: ['sh', '-c', 'until nc -z -v -w5 redis-service 6379; do echo "waiting for redis"; sleep 2; done;']
      containers:
      - name: python-api
        image: lab3:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          value: redis://redis-service.default.svc.cluster.local
        readinessProbe:
          httpGet:
            path: /lab/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /lab/health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /lab/health
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
