apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis  # Select pods with the label "app: redis"
  ports:
  - protocol: TCP
    port: 6379  # The port that the service exposes
    targetPort: 6379  # The port that the pods are listening on
